# Generated by Django 4.2.7 on 2023-12-15 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('tel', models.BigIntegerField()),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('DOB', models.DateField()),
                ('Gender', models.CharField(max_length=20)),
                ('work_as', models.CharField(max_length=100)),
                ('father_first_name', models.CharField(max_length=100)),
                ('father_last_name', models.CharField(max_length=100)),
                ('interest', models.CharField(max_length=100)),
                ('ph_number', models.BigIntegerField()),
                ('alt_number', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('add', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pin_code', models.IntegerField()),
                ('country', models.CharField(max_length=150)),
                ('college', models.CharField(max_length=200)),
                ('course_desc', models.TextField()),
                ('company', models.CharField(max_length=150)),
                ('work_desc', models.TextField()),
                ('adhar', models.ImageField(upload_to='')),
                ('bar_certificate', models.ImageField(upload_to='')),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
