# Generated by Django 4.2.7 on 2023-12-15 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_serviceprovider_user_alter_serviceprovider_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceprovider',
            name='username',
        ),
    ]
