# Generated by Django 4.2.7 on 2023-12-15 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_serviceprovider_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovider',
            name='DOB',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
