# Generated by Django 4.2.7 on 2023-12-15 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_serviceprovider_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceprovider',
            name='password',
        ),
    ]
