# Generated by Django 4.2.7 on 2023-12-15 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_serviceprovider_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceprovider',
            name='user',
        ),
    ]
